dist: xenial
sudo: required
branches:
  only:
  - master
  - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
git:
  depth: false
language: go
go:
- "1.11.x"
script: echo $TRAVIS_COMMIT_RANGE
