branches:
  only:
  - master
  - "/^v([0-9]+)\\.([0-9]+)\\.([0-9]+)(?:\\-(rc\\.[0-9]+)*)?$/"
language: go

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./b
  - bash <(curl -s https://codecov.io/bash) -c -F b
